[E 2023-04-13 10:49:57,443 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:49:57,959 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:49:58,464 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:49:58,978 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:49:59,494 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:49:59,997 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:55:39,812 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:55:40,317 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:55:40,825 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:55:41,331 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:55:41,836 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:55:42,336 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:56:52,810 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:56:53,317 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:56:53,822 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:56:54,326 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:56:54,832 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 10:56:55,347 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:36:32,460 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:36:32,978 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:36:33,493 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:36:33,999 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:36:34,505 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:36:35,009 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:40:51,425 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:40:51,930 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:40:52,435 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:40:52,939 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:40:53,441 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:40:53,945 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:41:11,316 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:41:11,831 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:41:12,334 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:41:12,849 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:41:13,352 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:41:13,854 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:43:27,167 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:43:27,670 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:43:28,175 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:43:28,676 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:43:29,181 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:43:29,686 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:43:46,124 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:43:46,628 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:43:47,132 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:43:47,639 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:43:48,143 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:43:48,646 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:44:22,011 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:44:22,515 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:44:23,023 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:44:23,529 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:44:24,031 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:44:24,536 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:44:58,551 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:44:59,054 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:44:59,568 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:45:00,074 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:45:00,577 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 11:45:01,079 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:33:02,506 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:33:03,009 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:33:03,513 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:33:04,020 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:33:04,523 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:33:05,028 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:33:34,864 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:33:35,367 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:33:35,872 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:33:36,377 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:33:36,880 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:33:37,385 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:49:16,197 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:49:16,703 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:49:17,212 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:49:17,718 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:49:18,228 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:49:18,736 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:50:20,397 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:50:20,902 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:50:21,407 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:50:21,915 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:50:22,420 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:50:22,923 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:50:56,009 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:50:56,514 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:50:57,021 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:50:57,525 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:50:58,029 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:50:58,536 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:51:25,429 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:51:25,934 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:51:26,437 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:51:26,945 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:51:27,451 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:51:27,959 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:57:21,532 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:57:22,035 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:57:22,539 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:57:23,046 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:57:23,549 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 13:57:24,054 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:06:25,835 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:06:26,340 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:06:26,845 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:06:27,352 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:06:27,856 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:06:28,361 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:07:45,432 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:07:45,949 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:07:46,456 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:07:46,965 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:07:47,468 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:07:47,972 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:08:47,059 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:08:47,577 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:08:48,081 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:08:48,582 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:08:49,086 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:08:49,591 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:09:06,159 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:09:06,661 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:09:07,169 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:09:07,673 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:09:08,180 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:09:08,684 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:10:43,548 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:10:44,048 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:10:44,551 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:10:45,056 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:10:45,562 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:10:46,065 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:15:59,533 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:16:00,039 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:16:00,547 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:16:01,051 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:16:01,555 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:16:02,063 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:16:15,699 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:16:16,216 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:16:16,721 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:16:17,224 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:16:17,730 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:16:18,235 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:17:22,059 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:17:22,565 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:17:23,072 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:17:23,578 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:17:24,089 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:17:24,599 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:17:57,872 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:17:58,380 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:17:58,886 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:17:59,393 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:17:59,895 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:18:00,404 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:18:26,252 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:18:26,756 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:18:27,263 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:18:27,769 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:18:28,278 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:18:28,780 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:19:23,573 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:19:24,078 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:19:24,581 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:19:25,088 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:19:25,592 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:19:26,094 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:20:23,913 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:20:24,420 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:20:24,924 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:20:25,434 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:20:25,938 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:20:26,443 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:22:16,409 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:22:16,917 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:22:17,419 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:22:17,924 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:22:18,431 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:22:18,941 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:23:14,760 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:23:15,267 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:23:18,591 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:23:19,093 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:23:19,597 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:23:20,098 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:23:20,606 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:23:21,113 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:24:01,279 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:24:01,788 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:24:02,293 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:24:02,810 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:24:03,310 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-13 17:24:03,812 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:28:01,564 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:28:02,071 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:28:02,575 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:28:03,079 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:28:03,583 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:28:04,090 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:29:45,538 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:29:46,042 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:29:46,546 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:29:47,053 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:29:47,558 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:29:48,063 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:30:36,975 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:30:37,480 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:30:37,984 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:30:38,487 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:30:38,996 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:30:39,501 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:32:20,540 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:32:21,050 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:32:21,551 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:32:22,056 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:32:22,558 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:32:23,063 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:35:24,847 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:35:25,353 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:35:25,859 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:35:26,362 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:35:26,868 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:35:27,373 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:37:10,336 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:37:10,839 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:37:11,344 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:37:11,851 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:37:12,356 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:37:12,859 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:39:10,261 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:39:10,767 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:39:11,275 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:39:11,781 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:39:12,285 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:39:12,792 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:39:59,745 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:40:00,249 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:40:00,752 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:40:01,257 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:40:01,763 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:40:02,270 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:52:21,157 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:52:21,663 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:52:22,164 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:52:22,672 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:52:23,186 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:52:23,689 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:54:48,322 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:54:48,838 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:54:49,340 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:54:49,856 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:54:50,357 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:54:50,862 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:56:18,942 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:56:19,445 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:56:19,946 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:56:20,453 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:56:20,960 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:56:21,467 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:57:28,993 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:57:29,496 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:57:30,001 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:57:30,504 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:57:31,008 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:57:31,511 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:57:49,345 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:57:49,861 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:57:50,365 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:57:50,866 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:57:51,373 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:57:51,875 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:58:07,730 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:58:08,236 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:58:08,737 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:58:09,240 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:58:09,740 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:58:10,244 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:59:56,127 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:59:56,645 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:59:57,146 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:59:57,650 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:59:58,155 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 08:59:58,659 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:00:14,942 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:00:15,445 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:00:15,950 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:00:16,455 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:00:16,958 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:00:17,464 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:06:59,607 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:07:00,113 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:07:00,619 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:07:01,126 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:07:01,628 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:07:02,135 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:07:48,453 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:07:48,957 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:07:49,463 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:07:49,965 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:07:50,467 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:07:50,969 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:09:47,076 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:09:47,591 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:09:48,096 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:09:48,600 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:09:49,103 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:09:49,606 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:27:46,912 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:27:47,414 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:27:47,914 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:27:48,429 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:27:48,930 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:27:49,433 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:28:20,409 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:28:20,911 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:28:21,414 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:28:21,919 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:28:22,436 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 09:28:22,937 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 10:05:12,585 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 10:05:13,099 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 10:05:13,604 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 10:05:14,106 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 10:05:14,609 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 10:05:15,113 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 10:09:47,813 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 10:09:48,316 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 10:09:48,817 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 10:09:49,323 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 10:09:49,825 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 10:09:50,327 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:16:20,861 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:16:21,366 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:16:21,872 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:16:22,375 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:16:22,881 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:16:23,389 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:18:15,753 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:18:16,256 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:18:16,759 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:18:17,266 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:18:17,772 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:18:18,277 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:20:28,169 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:20:28,672 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:20:29,177 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:20:29,683 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:20:30,186 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:20:30,694 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:23:06,025 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:23:06,529 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:23:07,031 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:23:07,537 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:23:08,045 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:23:08,548 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:24:09,405 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:24:09,906 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:24:10,411 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:24:10,915 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:24:11,423 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:24:11,933 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:26:31,643 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:26:32,152 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:26:32,658 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:26:33,162 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:26:33,667 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:26:34,173 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:30:48,800 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:30:49,306 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:30:49,813 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:30:50,317 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:30:50,825 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:30:51,328 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:33:59,890 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:34:00,395 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:34:00,900 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:34:01,407 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:34:01,912 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:34:02,418 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:35:10,579 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:35:11,083 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:35:11,588 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:35:12,094 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:35:12,601 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:35:13,105 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:36:15,128 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:36:15,643 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:36:16,154 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:36:16,659 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:36:17,163 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:36:17,669 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:37:40,450 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:37:40,959 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:37:41,460 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:37:41,965 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:37:42,468 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:37:42,974 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:37:56,632 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:37:57,135 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:37:57,644 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:37:58,150 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:37:58,651 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:37:59,158 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:39:07,844 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:39:08,349 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:39:08,855 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:39:09,360 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:39:09,870 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:39:10,375 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:40:54,958 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:40:55,460 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:40:55,966 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:40:56,469 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:40:56,975 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:40:57,480 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:42:22,483 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:42:22,989 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:42:23,498 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:42:24,001 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:42:24,506 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:42:25,009 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:43:32,180 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:43:32,683 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:43:33,186 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:43:33,694 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:43:34,200 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:43:34,706 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:45:06,539 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:45:07,041 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:45:07,548 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:45:08,054 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:45:08,558 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:45:09,063 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:46:49,936 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:46:50,440 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:46:50,945 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:46:51,449 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:46:51,953 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:46:52,457 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:47:39,400 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:47:39,904 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:47:40,410 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:47:40,915 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:47:41,419 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:47:41,925 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:50:50,114 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:50:50,628 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:50:51,135 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:50:51,637 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:50:52,139 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:50:52,640 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:53:26,947 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:53:27,451 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:53:27,957 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:53:28,462 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:53:28,965 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:53:29,469 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:58:13,382 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:58:13,885 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:58:14,396 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:58:14,903 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:58:15,409 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:58:15,916 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:59:13,809 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:59:14,315 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:59:14,820 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:59:15,324 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:59:15,830 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 14:59:16,333 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:06,121 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:06,626 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:07,127 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:07,641 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:08,144 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:08,647 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:33,712 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:34,217 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:34,720 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:35,222 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:35,725 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:36,227 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:50,999 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:51,503 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:52,009 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:52,511 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:53,012 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:00:53,517 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:08:23,672 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:08:24,177 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:08:24,682 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:08:25,187 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:08:25,692 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:08:26,197 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:08:57,806 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:08:58,309 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:08:58,811 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:08:59,314 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:08:59,816 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:09:00,320 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:11:11,273 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:11:11,776 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:11:12,281 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:11:12,782 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:11:13,284 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:11:13,784 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:17:19,101 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:17:19,617 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:17:20,119 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:17:20,623 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:17:21,125 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:17:21,629 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:17:57,262 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:17:57,765 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:17:58,269 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:17:58,773 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:17:59,277 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:17:59,781 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:21:34,875 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:21:35,383 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:21:35,887 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:21:36,390 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:21:36,895 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:21:37,401 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:22:00,952 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:22:01,468 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:22:01,973 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:22:02,478 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:22:02,984 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:22:03,490 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:24:51,178 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:24:51,682 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:24:52,184 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:24:52,685 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:24:53,188 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 15:24:53,697 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 16:28:18,178 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 16:28:18,682 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 16:28:19,186 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 16:28:19,691 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 16:28:20,198 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-14 16:28:20,703 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 10:44:29,994 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 10:44:30,498 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 10:44:31,001 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 10:44:31,502 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 10:44:32,006 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 10:44:32,510 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:01:52,448 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:01:52,962 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:01:53,466 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:01:53,969 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:01:54,471 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:01:54,986 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:03:08,766 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:03:09,268 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:03:09,771 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:03:10,274 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:03:10,774 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:03:11,287 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:09:48,114 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:09:48,627 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:09:49,128 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:09:49,632 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:09:50,134 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:09:50,637 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:10:21,088 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:10:21,603 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:10:22,108 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:10:22,609 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:10:23,122 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:10:23,639 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:10:46,439 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:10:46,956 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:10:47,472 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:10:47,985 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:10:48,485 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:10:48,989 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:17:25,712 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:17:26,217 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:17:26,719 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:17:27,233 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:17:27,735 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:17:28,238 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:17:52,764 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:17:53,282 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:17:53,782 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:17:54,283 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:17:54,788 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:17:55,293 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:28:13,221 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:28:13,735 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:28:14,251 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:28:14,754 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:28:15,259 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:28:15,761 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:30:50,106 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:30:50,609 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:30:51,116 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:30:51,630 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:30:52,130 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:30:52,633 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:31:12,420 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:31:12,924 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:31:13,425 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:31:13,931 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:31:14,433 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:31:14,937 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:36:40,276 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:36:40,778 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:36:41,291 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:36:41,793 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:36:42,298 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:36:42,798 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:37:09,924 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:37:10,427 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:37:10,930 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:37:11,431 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:37:11,933 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:37:12,435 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:39:51,569 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:39:52,083 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:39:52,594 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:39:53,100 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:39:53,613 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 11:39:54,130 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:00:44,079 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:00:44,580 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:00:45,082 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:00:45,586 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:00:46,088 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:00:46,604 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:01:40,081 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:01:40,596 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:01:41,096 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:01:41,599 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:01:42,100 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:01:42,603 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:03:29,277 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:03:29,778 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:03:30,282 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:03:30,797 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:03:31,298 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:03:31,799 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:04:01,915 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:04:02,428 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:04:02,943 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:04:03,444 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:04:03,958 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:04:04,459 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:04:39,799 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:04:40,314 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:04:40,815 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:04:41,320 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:04:41,822 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:04:42,324 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:05:02,848 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:05:03,350 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:05:03,864 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:05:04,367 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:05:04,871 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:05:05,373 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:05:56,332 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:05:56,849 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:05:57,363 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:05:57,877 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:05:58,379 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:05:58,882 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:06:31,883 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:06:32,398 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:06:32,901 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:06:33,417 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:06:33,919 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:06:34,422 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:06:51,663 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:06:52,167 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:06:52,669 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:06:53,172 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:06:53,673 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:06:54,180 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:07:37,325 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:07:37,840 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:07:38,341 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:07:38,855 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:07:39,357 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:07:39,859 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:17:29,106 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:17:29,621 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:17:30,125 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:17:30,625 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:17:31,127 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:17:31,630 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:18:18,912 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:18:19,414 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:18:19,917 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:18:20,432 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:18:20,946 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:18:21,448 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:19:38,624 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:19:39,126 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:19:39,630 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:19:40,134 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:19:40,636 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 13:19:41,138 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:36:12,701 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:36:13,207 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:36:13,712 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:36:14,218 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:36:14,721 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:36:15,227 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:38:15,798 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:38:16,302 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:38:16,805 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:38:17,307 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:38:17,810 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:38:18,318 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:38:55,605 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:38:56,109 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:38:56,611 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:38:57,116 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:38:57,621 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:38:58,128 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:44:54,651 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:44:55,159 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:44:55,663 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:44:56,170 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:44:56,676 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:44:57,180 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:45:22,091 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:45:22,599 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:45:23,101 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:45:23,604 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:45:24,107 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:45:24,614 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:46:26,689 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:46:27,195 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:46:27,701 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:46:28,206 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:46:28,707 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:46:29,214 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:47:07,172 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:47:07,686 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:47:08,191 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:47:08,696 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:47:09,207 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:47:09,714 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:50:39,836 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:50:40,343 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:50:40,853 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:50:41,358 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:50:41,861 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-17 14:50:42,364 C:\Users\011803\Anaconda3\envs\py3.8.3_env\lib\site-packages\shioaji\shioaji.py:222:_setup_solace] RequestException URLError('unknown url type: https')
[E 2023-04-21 11:30:16,234 C:\Users\012480\AppData\Local\Anaconda\lib\site-packages\shioaji\utils.py:46:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': 'Incorrect userid or password', 'ip_address': '128.110.23.84', 'client_name': '', 'contract_download': False, 'web_token': ''}}
[E 2023-04-21 11:30:18,961 C:\Users\012480\AppData\Local\Anaconda\lib\site-packages\shioaji\utils.py:46:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': 'Incorrect userid or password', 'ip_address': '128.110.23.84', 'client_name': '', 'contract_download': False, 'web_token': ''}}
[E 2023-04-21 13:51:03,805 c:\Users\012480\AppData\Local\Anaconda\lib\site-packages\shioaji\utils.py:46:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': 'Incorrect userid or password', 'ip_address': '128.110.23.84', 'client_name': '', 'contract_download': False, 'web_token': ''}}
[E 2023-04-21 14:02:37,477 c:\Users\012480\AppData\Local\Anaconda\lib\site-packages\shioaji\utils.py:46:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': 'Incorrect userid or password', 'ip_address': '128.110.23.84', 'client_name': '', 'contract_download': False, 'web_token': ''}}
[E 2023-04-21 17:38:19,676 c:\Users\012480\AppData\Local\Anaconda\lib\site-packages\shioaji\utils.py:46:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': 'Incorrect userid or password', 'ip_address': '128.110.23.84', 'client_name': '', 'contract_download': False, 'web_token': ''}}
[E 2023-04-21 17:43:11,051 c:\Users\012480\AppData\Local\Anaconda\lib\site-packages\shioaji\utils.py:46:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': 'Incorrect userid or password', 'ip_address': '128.110.23.84', 'client_name': '', 'contract_download': False, 'web_token': ''}}
[E 2023-04-21 17:43:17,392 c:\Users\012480\AppData\Local\Anaconda\lib\site-packages\shioaji\utils.py:46:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': 'Incorrect userid or password', 'ip_address': '128.110.23.84', 'client_name': '', 'contract_download': False, 'web_token': ''}}
[E 2023-04-21 17:43:26,263 c:\Users\012480\AppData\Local\Anaconda\lib\site-packages\shioaji\utils.py:46:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': 'Incorrect userid or password', 'ip_address': '128.110.23.84', 'client_name': '', 'contract_download': False, 'web_token': ''}}
[E 2023-04-21 17:48:45,574 c:\Users\012480\AppData\Local\Anaconda\lib\site-packages\shioaji\utils.py:46:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': 'Incorrect userid or password', 'ip_address': '128.110.23.84', 'client_name': '', 'contract_download': False, 'web_token': ''}}
